// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "camera_lcm_msgs_PositionGravityState.h"

static int __camera_lcm_msgs_PositionGravityState_hash_computed;
static uint64_t __camera_lcm_msgs_PositionGravityState_hash;

uint64_t __camera_lcm_msgs_PositionGravityState_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __camera_lcm_msgs_PositionGravityState_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __camera_lcm_msgs_PositionGravityState_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xde320c54bcbe0ce7LL
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __camera_lcm_msgs_PositionGravityState_get_hash(void)
{
    if (!__camera_lcm_msgs_PositionGravityState_hash_computed) {
        __camera_lcm_msgs_PositionGravityState_hash = (int64_t)__camera_lcm_msgs_PositionGravityState_hash_recursive(NULL);
        __camera_lcm_msgs_PositionGravityState_hash_computed = 1;
    }

    return __camera_lcm_msgs_PositionGravityState_hash;
}

int __camera_lcm_msgs_PositionGravityState_encode_array(void *buf, int offset, int maxlen, const camera_lcm_msgs_PositionGravityState *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].gravity, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].data, 18);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int camera_lcm_msgs_PositionGravityState_encode(void *buf, int offset, int maxlen, const camera_lcm_msgs_PositionGravityState *p)
{
    int pos = 0, thislen;
    int64_t hash = __camera_lcm_msgs_PositionGravityState_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __camera_lcm_msgs_PositionGravityState_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __camera_lcm_msgs_PositionGravityState_encoded_array_size(const camera_lcm_msgs_PositionGravityState *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __float_encoded_array_size(p[element].gravity, 3);

        size += __float_encoded_array_size(p[element].data, 18);

    }
    return size;
}

int camera_lcm_msgs_PositionGravityState_encoded_size(const camera_lcm_msgs_PositionGravityState *p)
{
    return 8 + __camera_lcm_msgs_PositionGravityState_encoded_array_size(p, 1);
}

int __camera_lcm_msgs_PositionGravityState_decode_array(const void *buf, int offset, int maxlen, camera_lcm_msgs_PositionGravityState *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].gravity, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].data, 18);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __camera_lcm_msgs_PositionGravityState_decode_array_cleanup(camera_lcm_msgs_PositionGravityState *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_decode_array_cleanup(p[element].gravity, 3);

        __float_decode_array_cleanup(p[element].data, 18);

    }
    return 0;
}

int camera_lcm_msgs_PositionGravityState_decode(const void *buf, int offset, int maxlen, camera_lcm_msgs_PositionGravityState *p)
{
    int pos = 0, thislen;
    int64_t hash = __camera_lcm_msgs_PositionGravityState_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __camera_lcm_msgs_PositionGravityState_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int camera_lcm_msgs_PositionGravityState_decode_cleanup(camera_lcm_msgs_PositionGravityState *p)
{
    return __camera_lcm_msgs_PositionGravityState_decode_array_cleanup(p, 1);
}

int __camera_lcm_msgs_PositionGravityState_clone_array(const camera_lcm_msgs_PositionGravityState *p, camera_lcm_msgs_PositionGravityState *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_clone_array(p[element].gravity, q[element].gravity, 3);

        __float_clone_array(p[element].data, q[element].data, 18);

    }
    return 0;
}

camera_lcm_msgs_PositionGravityState *camera_lcm_msgs_PositionGravityState_copy(const camera_lcm_msgs_PositionGravityState *p)
{
    camera_lcm_msgs_PositionGravityState *q = (camera_lcm_msgs_PositionGravityState*) malloc(sizeof(camera_lcm_msgs_PositionGravityState));
    __camera_lcm_msgs_PositionGravityState_clone_array(p, q, 1);
    return q;
}

void camera_lcm_msgs_PositionGravityState_destroy(camera_lcm_msgs_PositionGravityState *p)
{
    __camera_lcm_msgs_PositionGravityState_decode_array_cleanup(p, 1);
    free(p);
}

int camera_lcm_msgs_PositionGravityState_publish(lcm_t *lc, const char *channel, const camera_lcm_msgs_PositionGravityState *p)
{
      int max_data_size = camera_lcm_msgs_PositionGravityState_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = camera_lcm_msgs_PositionGravityState_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _camera_lcm_msgs_PositionGravityState_subscription_t {
    camera_lcm_msgs_PositionGravityState_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void camera_lcm_msgs_PositionGravityState_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    camera_lcm_msgs_PositionGravityState p;
    memset(&p, 0, sizeof(camera_lcm_msgs_PositionGravityState));
    status = camera_lcm_msgs_PositionGravityState_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding camera_lcm_msgs_PositionGravityState!!!\n", status);
        return;
    }

    camera_lcm_msgs_PositionGravityState_subscription_t *h = (camera_lcm_msgs_PositionGravityState_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    camera_lcm_msgs_PositionGravityState_decode_cleanup (&p);
}

camera_lcm_msgs_PositionGravityState_subscription_t* camera_lcm_msgs_PositionGravityState_subscribe (lcm_t *lcm,
                    const char *channel,
                    camera_lcm_msgs_PositionGravityState_handler_t f, void *userdata)
{
    camera_lcm_msgs_PositionGravityState_subscription_t *n = (camera_lcm_msgs_PositionGravityState_subscription_t*)
                       malloc(sizeof(camera_lcm_msgs_PositionGravityState_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 camera_lcm_msgs_PositionGravityState_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg camera_lcm_msgs_PositionGravityState LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int camera_lcm_msgs_PositionGravityState_subscription_set_queue_capacity (camera_lcm_msgs_PositionGravityState_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int camera_lcm_msgs_PositionGravityState_unsubscribe(lcm_t *lcm, camera_lcm_msgs_PositionGravityState_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe camera_lcm_msgs_PositionGravityState_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

